### Get subscriptionById
GET http://localhost:8080/subscriptions/2


### Create subscription
POST http://localhost:8080/subscriptions
Content-Type: application/json

{
  "beginDate": "2023-08-22",
  "endDate": "2023-09-22",
  "status": "ACTIVE",
  "subscriptionType": "SIX",
  "userId": 2
}








