### Get userById
GET http://localhost:8080/users/byId/1

### Get AllUsers
GET http://localhost:8080/users/allUsers

### Get userByPhoneNumber
GET http://localhost:8080/users/byPhone/123456789

### Get userByEmail
GET http://localhost:8080/users/byEmail/user2@example.com

### Create user
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "j2@jonekjoinek2.pl",
  "password": "pAssword!123",
  "firstName": "John",
  "lastName": "Doe",
  "birthdate": "1990-01-01",
  "phoneNumber": "12311a189"
}

### Update user
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "email": "updatedemail5@example.com",
  "password": "upDatedpassword456!",
  "firstName": "John",
  "lastName": "Doe",
  "birthdate": "1992-05-10",
  "phoneNumber": "123113189"
}

### Delete user
DELETE http://localhost:8080/users/3







